import type { TourStep } from '../components/tour/types';

// The Tutorial tour, in the order a new seller meets the register. Admin-only
// screens (Settings, Change PIN, Payment Options, QR codes) are left out on
// purpose. Copy follows the app's no em/en dash rule; a test enforces it.
//
// `target` ids are `TourTarget`s in the components. A list means "first one
// that exists" (portrait peek bar vs landscape side cart).

const HOME = '/';

export const TOUR_STEPS: TourStep[] = [
  {
    id: 'welcome',
    route: HOME,
    target: null,
    title: 'Welcome to Zoomy POS',
    body: 'A short walk through the register. The tour opens each screen for you, and nothing you see here is saved or charged.',
  },
  {
    id: 'event',
    route: HOME,
    target: 'event',
    title: 'Event badge',
    body: 'Shows which bazaar day you are selling on. Tap it to set up the event day.',
  },
  {
    id: 'sync',
    route: HOME,
    target: 'sync',
    title: 'Sync status',
    body: 'Shows whether your sales have reached Coop. The POS keeps working offline and catches up when the signal returns.',
  },
  {
    id: 'pills',
    route: HOME,
    target: 'pills',
    title: 'Categories',
    body: 'Filter the tiles by product line. Bundles shows the event deals, and Prize is for the spin the wheel.',
  },
  {
    id: 'grid',
    route: HOME,
    target: 'grid',
    title: 'Product tiles',
    body: 'Tap a tile to add it to the cart. A badge counts how many are in the sale, and a warning shows when stock is low.',
  },
  {
    id: 'variants',
    route: HOME,
    target: 'variant-options',
    title: 'Sizes and flavors',
    body: 'Products with variants open a picker first. Tap each variant to add it, then press Done.',
    auto: 'The tour taps a product that has variants',
    scene: { sheet: 'variant' },
  },
  {
    id: 'free-taste-sheet',
    route: HOME,
    target: 'quick-actions',
    title: 'Long press for a free taste',
    body: 'Hold any tile to log a free taste. It uses up stock for pets to sample, and it does not add to the sale.',
    auto: 'The tour long-presses a tile',
    scene: { sheet: 'free-taste' },
  },
  {
    id: 'pet',
    route: HOME,
    target: ['peek-pet', 'panel-pet'],
    title: 'Pet tag',
    body: 'Tag the sale as Dog, Cat or Both. Tap the chip again to clear it.',
  },
  {
    id: 'method',
    route: HOME,
    target: ['peek-method', 'panel-method'],
    title: 'Payment method',
    body: 'Pick how the customer pays. Your manager chooses which methods show up in Settings.',
  },
  {
    id: 'cart-total',
    route: HOME,
    target: ['peek-total', 'panel-lines'],
    title: 'Your cart',
    body: 'The item count and total of the current sale. A demo item was added for the tour.',
  },
  {
    id: 'cart-lines',
    route: HOME,
    target: 'panel-lines',
    title: 'Cart lines',
    body: 'Use plus and minus to change a quantity. The gift icon marks a line as a free prize, and the bin removes it.',
    auto: 'The tour opens the cart',
    scene: { cartExpanded: true },
  },
  {
    id: 'pay',
    route: HOME,
    target: ['peek-pay', 'panel-pay'],
    title: 'Pay',
    body: 'Tap Pay to finish the sale. By default it asks you to confirm first.',
  },
  {
    id: 'confirm-summary',
    route: HOME,
    target: 'confirm-summary',
    title: 'Confirm payment',
    body: 'Check the method and the total before you record the sale.',
    auto: 'The tour taps Pay (demo only)',
    scene: { sheet: 'confirm-pay' },
  },
  {
    id: 'confirm-handle',
    route: HOME,
    target: 'confirm-handle',
    title: 'Furbaby or IG handle',
    body: 'Optional. Add the customer’s Instagram handle or their pet’s name so you can tag them later.',
    scene: { sheet: 'confirm-pay' },
  },
  {
    id: 'confirm-actions',
    route: HOME,
    target: 'confirm-actions',
    title: 'Paid',
    body: 'Paid records the sale and starts a new one. In the tour it is blocked, so nothing is charged.',
    scene: { sheet: 'confirm-pay' },
  },
  {
    id: 'prize',
    route: HOME,
    target: ['prize-tile', 'grid'],
    title: 'Prizes',
    body: 'After the customer spins the wheel, tap the prize tile to pick what they won. It joins the cart as a free line.',
    auto: 'The tour selects the Prize pill',
    scene: { category: 'prize' },
  },
  {
    id: 'bundles',
    route: HOME,
    target: 'grid',
    title: 'Bundle deals',
    body: 'Event deals such as Buy Any 4 show up as tiles. Tap one to choose its flavors.',
    auto: 'The tour selects the Bundles pill',
    scene: { category: 'bundles' },
  },
  {
    id: 'bundle-flavors',
    route: '/modals/bundle-select?bundleId=:firstBundleId',
    target: 'bundle-progress',
    title: 'Choosing flavors',
    body: 'Tapping a bundle tile opens this screen. The counter shows how many picks the deal still needs.',
    auto: 'The tour opens a bundle deal',
  },
  {
    id: 'bundle-pick',
    route: '/modals/bundle-select?bundleId=:firstBundleId',
    target: 'bundle-flavors',
    title: 'Pick each flavor',
    body: 'Use plus and minus beside each flavor. The deal is full when the counter reaches its number.',
  },
  {
    id: 'bundle-add',
    route: '/modals/bundle-select?bundleId=:firstBundleId',
    target: 'bundle-add',
    title: 'Add to sale',
    body: 'When every pick is made, Add to sale puts the bundle in the cart at its deal price.',
  },
  {
    id: 'event-cash',
    route: '/modals/event-setup',
    target: 'event-cash',
    title: 'Opening cash',
    body: 'Enter the cash float you start the day with. A cash note is optional.',
    auto: 'The tour taps the event badge',
  },
  {
    id: 'event-closing',
    route: '/modals/event-setup',
    target: 'event-closing',
    title: 'Counted at close',
    body: 'At the end of the day, count the drawer and enter it here.',
  },
  {
    id: 'free-taste-tabs',
    route: '/modals/free-taste',
    target: 'ft-tabs',
    title: 'Free taste',
    body: 'Log treats you open for pets to sample. This deducts event stock, and no sale is made.',
    auto: 'The tour taps the Free taste icon',
    scene: { freeTasteTab: 'record' },
  },
  {
    id: 'free-taste-search',
    route: '/modals/free-taste',
    target: 'ft-search',
    title: 'Find a treat',
    body: 'Search or filter by category, then use plus and minus to set how many packs you opened.',
    scene: { freeTasteTab: 'record' },
  },
  {
    id: 'free-taste-record',
    route: '/modals/free-taste',
    target: 'ft-footer',
    title: 'Record',
    body: 'The packs opened total shows here. Tap Record to save them. Nothing is saved during the tour.',
    scene: { freeTasteTab: 'record' },
  },
  {
    id: 'free-taste-recent',
    route: '/modals/free-taste',
    target: ['ft-undo', 'ft-recent-hint'],
    title: 'Recent and Undo',
    body: 'See what was logged. Tapped the wrong one? Undo puts the packs back in stock.',
    auto: 'The tour opens the Recent tab',
    scene: { freeTasteTab: 'recent' },
  },
  {
    id: 'bundle-size',
    route: '/modals/bundle',
    target: 'bundle-size',
    title: 'Create a bundle deal',
    body: 'Set up a deal such as Buy Any 4 here. Choose how many flavors the customer picks.',
    auto: 'The tour taps the Bundle icon',
  },
  {
    id: 'bundle-lines',
    route: '/modals/bundle',
    target: 'bundle-lines',
    title: 'Product lines',
    body: 'Choose which product lines count toward the deal.',
  },
  {
    id: 'bundle-save',
    route: '/modals/bundle',
    target: 'bundle-save',
    title: 'Save bundle',
    body: 'Saving adds the deal to the Bundles pill on the register. Nothing is saved during the tour.',
  },
  {
    id: 'products-pills',
    route: '/modals/products',
    target: 'products-pills',
    title: 'Products by line',
    body: 'Filter the list by product line so you are not scrolling one long list.',
    auto: 'The tour taps the Products icon',
  },
  {
    id: 'products-row',
    route: '/modals/products',
    target: 'products-row',
    title: 'A product row',
    body: 'Each row shows the price. The pencil edits it, the bin deletes it, and the switch lists or unlists it on the register.',
  },
  {
    id: 'products-bundle',
    route: '/modals/products',
    target: 'products-bundle',
    title: 'Bundle presets',
    body: 'Your deals are listed here too, with the same edit, delete and switch controls.',
  },
  {
    id: 'tx-filters',
    route: '/modals/transactions',
    target: 'tx-filters',
    title: 'Filters',
    body: 'Choose a date range and a payment method.',
    auto: 'The tour taps the Transactions icon',
  },
  {
    id: 'tx-summary',
    route: '/modals/transactions',
    target: 'tx-summary',
    title: 'Totals and export',
    body: 'See how many sales match and what they add up to. Export saves them as a CSV.',
  },
  {
    id: 'tx-list',
    route: '/modals/transactions',
    target: 'tx-list',
    title: 'Every sale',
    body: 'Tap a sale for its items and payment details. Voiding a sale asks for the admin PIN, so ask your manager.',
  },
  {
    id: 'playbook-tabs',
    route: '/modals/playbook',
    target: 'playbook-tabs',
    title: 'Playbook',
    body: 'The booth script and product facts, always at hand when a customer asks.',
    auto: 'The tour taps the Playbook icon',
    scene: { playbookTab: 'flow' },
  },
  {
    id: 'playbook-step',
    route: '/modals/playbook',
    target: 'playbook-step',
    title: 'Paths and shortcuts',
    body: 'Pick the path that fits the customer. Some steps have a shortcut into the register, like Record a free taste.',
    scene: { playbookTab: 'flow' },
  },
  {
    id: 'playbook-filters',
    route: '/modals/playbook',
    target: 'playbook-filters',
    title: 'Product facts',
    body: 'Filter by Small, Big or Cats to find the right recommendation and its expiry.',
    auto: 'The tour opens the Products tab',
    scene: { playbookTab: 'products' },
  },
  {
    id: 'theme',
    route: HOME,
    target: 'header-action-theme',
    title: 'Light and dark',
    body: 'Switch the look for bright daytime booths or dim evening ones.',
    scene: { drawerOpen: true },
  },
  {
    id: 'replay',
    route: HOME,
    target: 'header-action-tutorial',
    title: 'Replay any time',
    body: 'Tap Tutorial to run this tour again. Happy selling!',
    scene: { drawerOpen: true },
  },
];
